export const jobs = [
  {
    id: 1,
    title: 'Front End Web Developer',
    company: 'Flipkart',
    position: 'Senior Software Enginner',
    jobType: 'Full-time',
    applicants: [],
    location: 'remote',
  },
  {
    id: 2,
    title: 'Full Stack Web Developer',
    company: 'Amazon',
    position: 'Senior Software Enginner',
    jobType: 'Full-time',
    applicants: [],
    location: 'remote',
  },
  {
    id: 13,
    title: 'Front End Web Developer',
    company: 'Unacademy',
    position: 'Senior Software Enginner',
    jobType: 'Full-time',
    applicants: [],
    location: 'remote',
  },
  {
    id: 4,
    title: 'Full Stack Web Developer',
    company: 'BigBinary',
    position: 'Senior Software Enginner',
    jobType: 'Full-time',
    applicants: [],
    location: 'remote',
  },
  {
    id: 5,
    title: 'Front End Web Developer',
    company: 'Netflix',
    position: 'Junior Software Enginner',
    jobType: 'Full-time',
    applicants: [],
    location: 'remote',
  },
  {
    id: 6,
    title: 'Full Stack Web Developer',
    company: 'Amazon',
    position: 'Senior Software Enginner',
    jobType: 'Full-time',
    applicants: [],
    location: 'remote',
  },
];
